title: "Muhammad Ishfaq Hussain"
description: "Personal academic & research portfolio of Muhammad Ishfaq Hussain (AI / Computer Vision / Large-Scale AI)."
url: "https://mi-hussain.github.io"
baseurl: ""   # keep empty for username.github.io sites

# also set:
name: "Muhammad Ishfaq Hussain"
email: "ishfaqhussain@gist.ac.kr"
